name: bug
title: Bug报告
description: 服务器内出现了不按预期运行的状况
assignees: IlyaYezelovsky
body:
  - type: dropdown
    id: dropdown-0
    attributes:
      label: Bug类别
      description: Bug出现在哪个方面？
    validations: 
      required: true
      options:
        - Essentials-一般命令
        - HuskHomes-传送命令
        - Residence-领地系统
        - QuickShop-经济系统
        - 游戏特性
        - 其他问题
  - type: textarea
    id: textarea-1
    attributes:
      label: Bug描述
    validations: 
      required: true
  - type: textarea
    id: textarea-2
    attributes:
      label: 预期的行为
    validations: 
      required: true
  - type: textarea
    id: textarea-3
    attributes:
      label: 复现步骤
    validations: 
      required: true
  - type: textarea
    id: textarea-4
    attributes:
      label: 其他信息
      description: 例如客户端Mod列表、日志等
    validations: 
      required: true
