name: bug
description: 报告服务器内不按预期运作的情况．
labels: bug
title: [Bug]
body:
- type: dropdown
    id: "category"
    attributes: 
    label: 问题类型
        options:
            - 游戏特性
            - 指令权限
            - 经济/领地
            - 其他问题
    validations:
        required: true
- type: textarea
    id: desc
    attributes:
        label: 问题描述
        placeholder: 我在使用xx时，发现…
    validations:
        required: true
- type: textarea
    id: repo
    attributes:
        label: 复现步骤
        description: 产生该Bug的步骤
        value: |
            1.
            2.
            3.
        validations:
            required: true
- type: checkboxes
    id: check
    attributes:
        label: 确认
        options:
            - label: 我确认我使用的是与服务端核心相同的客户端版本
                required: true
            - label: 我确认我可以复现我描述的Bug
                required: true
            - label: 我确认我已搜索过Issues内无重复提交
                required: true
