name: "建议 "
title: "[建议]"
description: 有关改进服务器的建议
assignees: IlyaYezelovsky
body:
  - type: textarea
    id: textarea-0
    attributes:
      label: 建议内容
    validations:
      required: true
  - type: textarea
    id: textarea-1
    attributes:
      label: 原因
    validations:
      required: false
  - type: textarea
    id: textarea-2
    attributes:
      label: 其他信息
    validations:
      required: false
